import{initializeApp}from"https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js";import{getAuth,signInAnonymously,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js";import{getDatabase,ref,set,get,onValue,update}from"https://www.gstatic.com/firebasejs/12.3.0/firebase-database.js";
const firebaseConfig={apiKey:"AIzaSyBIQKdOxb6kGa52zNNiK2xeJg__twpyVqk",authDomain:"jurado-de-diseno.firebaseapp.com",databaseURL:"https://jurado-de-diseno-default-rtdb.firebaseio.com",projectId:"jurado-de-diseno",storageBucket:"jurado-de-diseno.firebasestorage.app",messagingSenderId:"846826623599",appId:"1:846826623599:web:3b2668cbb9aa7594e7f39a"};const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app);
const S={mode:"home",code:"",session:null,student:null,ratings:{},teacherCriteria:[0,0,0,0,0],teacherName:"",teacherConnected:false,off:null};const $=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const toast=m=>{const e=document.createElement("div");e.className="toast";e.textContent=m;document.body.append(e);setTimeout(()=>e.remove(),2500)};const avatars=["🦊","🐼","🐸","🐯","🐙","🦄","🐝","🐧","🐨","🦁","🐵","🐰"];
let audioCtx=null;
function uiSound(kind="click"){try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==="suspended")audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain(),now=audioCtx.currentTime;o.type="sine";o.frequency.value=kind==="celebrate"?660:520;g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(kind==="celebrate"?.055:.018,now+.012);g.gain.exponentialRampToValueAtTime(.0001,now+(kind==="celebrate"?.55:.075));o.connect(g);g.connect(audioCtx.destination);o.start(now);o.stop(now+(kind==="celebrate"?.6:.09));if(kind==="celebrate"){setTimeout(()=>uiSound("celebrate2"),110)}}catch(e){}}
document.addEventListener("click",e=>{const b=e.target.closest("button");if(b&&!b.disabled)uiSound("click")});
function celebrationSound(){try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==="suspended")audioCtx.resume();[523,659,784,1047].forEach((hz,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime+i*.11;o.type="sine";o.frequency.value=hz;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.045,t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+.42);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+.45)})}catch(e){}}

function listen(){if(S.off)S.off();S.off=onValue(ref(db,"sessions/"+S.code),x=>{S.session=x.val();if(S.mode==="dashboard"){if(document.fullscreenElement&&$("#projection"))syncProjection(S.session);else dashboard()}if(S.mode==="student")studentRoom()})}
function home(){S.mode="home";document.getElementById("main").className="home-view";document.getElementById("main").innerHTML='<div class="hero"><div><div class="eyebrow">DAMB Creative</div><h1>Juzgar.<br><span style="color:var(--accent)">Analizar.</span><br>Mejorar.</h1><p>Una sala de evaluación profesional para estudiantes de diseño gráfico, con votación y resultados en tiempo real.</p></div></div><div class="modebar"><button class="active" id="t">Soy docente</button><button id="s">Soy estudiante</button></div><section id="panel" class="card"></section>';$("#t").onclick=teacher;$("#s").onclick=join;teacher()}
function teacher(){
document.querySelectorAll(".modebar button").forEach(x=>x.classList.remove("active"));
$("#t").classList.add("active");
$("#panel").innerHTML='<div class="grid"><div class="half"><h2>Crear una sesión</h2><p class="muted">Carga todos los trabajos de una vez. El nombre del estudiante se obtiene del nombre de cada archivo.</p><div class="field"><label>ACTIVIDAD</label><input id="title" value="Jurado de Diseño — Crítica visual"></div><div class="field"><label>DOCENTE</label><input id="teacher" placeholder="Daniel Martínez"></div><div class="field"><label>TRABAJOS DE LOS ESTUDIANTES</label><input id="batchFiles" type="file" accept="image/*" multiple webkitdirectory directory><small class="muted">Selecciona una carpeta completa o varios archivos. Ejemplo: <b>Juan_Perez.png</b> → Juan Perez.</small></div><div class="field"><label>SELECCIÓN INDIVIDUAL MÚLTIPLE</label><input id="multiFiles" type="file" accept="image/*" multiple></div><div id="batchPreview" class="muted" style="margin-top:8px">Aún no hay archivos seleccionados.</div></div><div class="half"><div class="field"><label>INSTRUCCIÓN DE CRÍTICA</label><textarea id="brief">Evalúa desde una perspectiva profesional. Reconoce decisiones visuales y señala oportunidades concretas de mejora.</textarea></div><div class="card" style="margin-top:14px;background:#111116"><h3>Formato</h3><p class="muted">Usa <b>Nombre_Apellido.ext</b>, <b>Nombre-Apellido.ext</b> o <b>Nombre Apellido.ext</b>.</p><p class="muted">Cada archivo se convierte en un estudiante y queda vinculado automáticamente con su trabajo.</p></div><button class="btn primary" id="create">Crear sesión y cargar trabajos</button></div></div><div class="card teacher-join-card"><div class="eyebrow">Acceso docente</div><h2>Unirse a una sesión existente</h2><p class="muted">El docente también puede entrar desde su celular usando el código proyectado en la sala.</p><div class="grid teacher-join-grid"><div class="half"><div class="field"><label>CÓDIGO DE SALA</label><input id="teacherCode" maxlength="6" placeholder="ABC123" style="text-align:center;text-transform:uppercase;font-size:22px;font-weight:800;letter-spacing:.12em"></div></div><div class="half"><div class="field"><label>NOMBRE DEL DOCENTE</label><input id="teacherJoinName" placeholder="Daniel Martínez"></div></div></div><button class="btn primary" id="joinTeacher">Entrar como docente</button></div></div>';
$("#create").onclick=createSession;
$("#batchFiles").onchange=updateBatchPreview;
$("#multiFiles").onchange=updateBatchPreview;
$("#joinTeacher").onclick=joinTeacher
}
function parseStudentName(filename){const base=filename.replace(/\.[^.]+$/,"").trim();return base.replace(/[_-]+/g," ").replace(/\s+/g," ").trim()||"Estudiante"}
function selectedBatchFiles(){const a=[...($("#batchFiles")?.files||[])],b=[...($("#multiFiles")?.files||[])],seen=new Set;return [...a,...b].filter(f=>{if(!f.type.startsWith("image/"))return false;const key=f.name+"|"+f.size+"|"+f.lastModified;if(seen.has(key))return false;seen.add(key);return true}).sort((x,y)=>x.name.localeCompare(y.name,"es",{numeric:true,sensitivity:"base"}))}
function updateBatchPreview(){const files=selectedBatchFiles(),el=$("#batchPreview");if(!el)return;el.innerHTML=files.length?"<b>"+files.length+" archivos listos.</b> "+files.map(f=>esc(parseStudentName(f.name))).join(" · "):"Aún no hay archivos seleccionados."}
async function createSession(){const files=selectedBatchFiles();const names=files.map(f=>parseStudentName(f.name));if(!names.length)return toast("Selecciona una carpeta o varios archivos");if(!auth.currentUser)return toast("Firebase aún no terminó de iniciar sesión");const students=names.map((name,i)=>({id:"s"+i,name,avatar:avatars[i%avatars.length]}));const teacherName=($("#teacher")?.value||"").trim()||"Docente";const code=Math.random().toString(36).slice(2,8).toUpperCase();const data={title:$("#title")?.value||"Jurado de Diseño",teacher:teacherName,brief:$("#brief")?.value||"",status:"lobby",current:0,createdAt:Date.now(),students:Object.fromEntries(students.map(x=>[x.id,x])),pieces:{},votes:{},teacherVotes:{}};try{await set(ref(db,"sessions/"+code),data);for(let i=0;i<files.length;i++){const f=files[i],owner=students[i],img=await compress(f);await set(ref(db,"sessions/"+code+"/pieces/"+i),{title:f.name.replace(/\.[^.]+$/,""),image:img,studentId:owner.id,studentName:owner.name,avatar:owner.avatar})}}catch(e){console.error("Firebase Database:",e);return toast("No se pudo crear/cargar la sesión: "+(e?.code||e?.message||"error"))}S.code=code;S.session=await get(ref(db,"sessions/"+code)).then(x=>x.val());S.teacherName=teacherName;S.teacherConnected=true;listen();dashboard();toast("Sesión creada: "+code)}

